import {IWeatherData} from "./common";

export const sampleData = {
    "queryCost": 1,
    "latitude": 47.4940529770015,
    "longitude": 19.056846683063,
    "resolvedAddress": "47.49405297700152, 19.056846683063025",
    "address": "47.49405297700152, 19.056846683063025",
    "timezone": "Europe/Budapest",
    "tzoffset": 1,
    "days": [
        {
            "datetime": "2025-01-06",
            "datetimeEpoch": 1736118000,
            "tempmax": 7.9,
            "tempmin": 0.4,
            "temp": 3.9,
            "feelslikemax": 6.5,
            "feelslikemin": 0.4,
            "feelslike": 3,
            "dew": 2.7,
            "humidity": 92.3,
            "precip": 0,
            "precipprob": 12.9,
            "precipcover": 0,
            "preciptype": null,
            "snow": 0,
            "snowdepth": 0,
            "windgust": 28.4,
            "windspeed": 11.2,
            "winddir": 153.2,
            "pressure": 1008.8,
            "cloudcover": 71.2,
            "visibility": 24.1,
            "solarradiation": 8.8,
            "solarenergy": 0.7,
            "uvindex": 0,
            "severerisk": 10,
            "sunrise": "07:31:02",
            "sunriseEpoch": 1736145062,
            "sunset": "16:08:43",
            "sunsetEpoch": 1736176123,
            "moonphase": 0.23,
            "conditions": "Részben felhős",
            "description": "Részben felhős egész nap.",
            "icon": "partly-cloudy-day",
            "stations": null,
            "source": "fcst"
        },
        {
            "datetime": "2025-01-07",
            "datetimeEpoch": 1736204400,
            "tempmax": 9.9,
            "tempmin": 4.7,
            "temp": 6.4,
            "feelslikemax": 9.6,
            "feelslikemin": 3.3,
            "feelslike": 5.5,
            "dew": 3.9,
            "humidity": 84.7,
            "precip": 2.8,
            "precipprob": 77.4,
            "precipcover": 41.67,
            "preciptype": [
                "rain"
            ],
            "snow": 0,
            "snowdepth": 0,
            "windgust": 36,
            "windspeed": 13.3,
            "winddir": 237.5,
            "pressure": 1010.1,
            "cloudcover": 96.6,
            "visibility": 21.1,
            "solarradiation": 29,
            "solarenergy": 2.5,
            "uvindex": 1,
            "severerisk": 10,
            "sunrise": "07:30:46",
            "sunriseEpoch": 1736231446,
            "sunset": "16:09:52",
            "sunsetEpoch": 1736262592,
            "moonphase": 0.25,
            "conditions": "Eső, Felhős",
            "description": "Felhős ég a nap folyamán, valamint esély esőre.",
            "icon": "rain",
            "stations": null,
            "source": "fcst"
        },
        {
            "datetime": "2025-01-08",
            "datetimeEpoch": 1736290800,
            "tempmax": 8.6,
            "tempmin": 1.5,
            "temp": 4.8,
            "feelslikemax": 7.7,
            "feelslikemin": 1.5,
            "feelslike": 4.5,
            "dew": 2.2,
            "humidity": 83.4,
            "precip": 0,
            "precipprob": 74.2,
            "precipcover": 0,
            "preciptype": [
                "rain"
            ],
            "snow": 0,
            "snowdepth": 0,
            "windgust": 21.2,
            "windspeed": 7.2,
            "winddir": 186.7,
            "pressure": 1012.8,
            "cloudcover": 73.9,
            "visibility": 24.1,
            "solarradiation": 41.3,
            "solarenergy": 3.6,
            "uvindex": 2,
            "severerisk": 10,
            "sunrise": "07:30:27",
            "sunriseEpoch": 1736317827,
            "sunset": "16:11:03",
            "sunsetEpoch": 1736349063,
            "moonphase": 0.3,
            "conditions": "Eső, Részben felhős",
            "description": "Részben felhős egész nap, valamint esély esőre.",
            "icon": "showers-day",
            "stations": null,
            "source": "fcst"
        },
        {
            "datetime": "2025-01-09",
            "datetimeEpoch": 1736377200,
            "tempmax": 10.3,
            "tempmin": 3.6,
            "temp": 6.7,
            "feelslikemax": 10.3,
            "feelslikemin": 2,
            "feelslike": 5.5,
            "dew": 4.9,
            "humidity": 88.1,
            "precip": 6.6,
            "precipprob": 64.5,
            "precipcover": 25,
            "preciptype": [
                "rain"
            ],
            "snow": 0,
            "snowdepth": 0,
            "windgust": 41.8,
            "windspeed": 14.8,
            "winddir": 180.4,
            "pressure": 1008.9,
            "cloudcover": 83.7,
            "visibility": 22.7,
            "solarradiation": 20.5,
            "solarenergy": 1.7,
            "uvindex": 1,
            "severerisk": 10,
            "sunrise": "07:30:05",
            "sunriseEpoch": 1736404205,
            "sunset": "16:12:16",
            "sunsetEpoch": 1736435536,
            "moonphase": 0.34,
            "conditions": "Eső, Részben felhős",
            "description": "Részben felhős egész nap, valamint késő délutáni eső.",
            "icon": "showers-day",
            "stations": null,
            "source": "fcst"
        },
        {
            "datetime": "2025-01-10",
            "datetimeEpoch": 1736463600,
            "tempmax": 10.4,
            "tempmin": 1.2,
            "temp": 4.4,
            "feelslikemax": 10.4,
            "feelslikemin": -4.6,
            "feelslike": -0.3,
            "dew": 0.3,
            "humidity": 74.9,
            "precip": 3.3,
            "precipprob": 64.5,
            "precipcover": 16.67,
            "preciptype": [
                "rain",
                "snow"
            ],
            "snow": 0,
            "snowdepth": 0,
            "windgust": 66.6,
            "windspeed": 36.4,
            "winddir": 309.7,
            "pressure": 1009.9,
            "cloudcover": 85,
            "visibility": 23.1,
            "solarradiation": 21,
            "solarenergy": 1.8,
            "uvindex": 1,
            "severerisk": 10,
            "sunrise": "07:29:40",
            "sunriseEpoch": 1736490580,
            "sunset": "16:13:30",
            "sunsetEpoch": 1736522010,
            "moonphase": 0.38,
            "conditions": "Hó, Eső, Részben felhős",
            "description": "Részben felhős egész nap, valamint Eső vagy havazás lecsendesül később.",
            "icon": "showers-day",
            "stations": null,
            "source": "fcst"
        }
    ],
    "stations": {
        "E4670": {
            "distance": 1934,
            "latitude": 47.478,
            "longitude": 19.047,
            "useCount": 0,
            "id": "E4670",
            "name": "EW4670 Budapest HU",
            "quality": 0,
            "contribution": 0
        },
        "E3429": {
            "distance": 6972,
            "latitude": 47.556,
            "longitude": 19.068,
            "useCount": 0,
            "id": "E3429",
            "name": "EW3429 Budapest HU",
            "quality": 0,
            "contribution": 0
        },
        "LHBP": {
            "distance": 17555,
            "latitude": 47.43,
            "longitude": 19.27,
            "useCount": 0,
            "id": "LHBP",
            "name": "LHBP",
            "quality": 50,
            "contribution": 0
        }
    },
    "currentConditions": {
        "datetime": "12:25:00",
        "datetimeEpoch": 1736076300,
        "temp": -1.1,
        "feelslike": -1.1,
        "humidity": 82.6,
        "dew": -3.7,
        "precip": 0,
        "precipprob": 0,
        "snow": 0,
        "snowdepth": 0,
        "preciptype": null,
        "windgust": 8.2,
        "windspeed": 3.3,
        "winddir": 181,
        "pressure": 1014,
        "visibility": 10,
        "cloudcover": 100,
        "solarradiation": 68,
        "solarenergy": 0.2,
        "uvindex": 1,
        "conditions": "Felhős",
        "icon": "cloudy",
        "stations": [
            "E4670",
            "E3429",
            "LHBP"
        ],
        "source": "obs",
        "sunrise": "07:31:16",
        "sunriseEpoch": 1736058676,
        "sunset": "16:07:36",
        "sunsetEpoch": 1736089656,
        "moonphase": 0.2
    }
} as IWeatherData;
